[tool.poetry]
name = "greetpkg"
version = "0.1.1"
description = ""
authors = ["Alejandro Medina Díaz <aresempai@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.10"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
